// @ts-nocheck
import type { Metadata } from "next";
import Link from "next/link";
import Image from "next/image";
import { Sparkles, Cpu, ChevronRight, Zap } from "lucide-react";
import { getAiInsight } from "@/lib/queries";
import { createClient } from "@/lib/supabase/server";

interface Props {
  params: Promise<{ slug: string }>;
}

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { slug } = await params;
  const name = slug.replace(/-/g, " ").replace(/\b\w/g, (c) => c.toUpperCase());
  return { title: `${name} — Chipset Insight`, description: `AI breakdown of the ${name} chipset — performance, benchmarks, and devices.` };
}

export default async function ChipsetInsightPage({ params }: Props) {
  const { slug } = await params;
  const chipsetName = slug.replace(/-/g, " ").replace(/\b\w/g, (c) => c.toUpperCase());
  const insight = await getAiInsight("chipset", slug);

  // Devices with this chipset
  const supabase = await createClient();
  const searchTerm = chipsetName.split("(")[0].trim();
  const { data: specRows } = await supabase
    .from("specifications")
    .select("device_id")
    .eq("spec_name", "Chipset")
    .ilike("spec_value", `%${searchTerm}%`)
    .limit(60);

  const deviceIds = [...new Set(specRows?.map((s) => s.device_id).filter(Boolean) ?? [])].slice(0, 12);

  const { data: devices } = deviceIds.length
    ? await supabase.from("devices").select("id,name,slug,image_url,company:companies(name,slug)").in("id", deviceIds)
    : { data: [] };

  const content = insight?.content as Record<string, any> | null;

  return (
    <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-10">
      <nav className="flex items-center gap-1.5 text-sm text-slate-500 mb-6">
        <Link href="/" className="hover:text-slate-300">Home</Link>
        <ChevronRight size={14} />
        <span className="text-slate-300">Chipset Insight: {chipsetName}</span>
      </nav>

      {/* Header */}
      <div className="ai-glow rounded-2xl p-8 mb-8">
        <div className="flex items-center gap-2 text-brand-400 font-semibold mb-3">
          <Sparkles size={20} /> AI Chipset Insight
        </div>
        <h1 className="text-4xl font-bold text-white mb-3 flex items-center gap-3">
          <Cpu size={32} className="text-brand-400" /> {chipsetName}
        </h1>
        {content?.tagline && <p className="text-slate-300 text-lg">{content.tagline}</p>}
        {insight && <p className="text-xs text-slate-600 mt-3">Generated by {insight.model_used} · {new Date(insight.generated_at).toLocaleDateString()}</p>}
      </div>

      {content ? (
        <div className="space-y-6">
          {content.overview && (
            <div className="card p-6">
              <h2 className="text-lg font-bold text-white mb-3">Overview</h2>
              <p className="text-slate-300 leading-relaxed">{content.overview}</p>
            </div>
          )}

          {/* Specs grid */}
          {content.specs && (
            <div className="card p-6">
              <h2 className="text-lg font-bold text-white mb-4">Technical Specs</h2>
              <div className="grid sm:grid-cols-2 gap-2">
                {Object.entries(content.specs as Record<string, string>).map(([k, v]) => (
                  <div key={k} className="flex justify-between text-sm py-2 border-b border-[#334155]/50">
                    <span className="text-slate-500">{k}</span>
                    <span className="text-slate-200 text-right">{v}</span>
                  </div>
                ))}
              </div>
            </div>
          )}

          <div className="grid sm:grid-cols-2 gap-4">
            {[
              { key: "cpu_performance",  label: "CPU Performance", icon: <Zap size={14} /> },
              { key: "gpu_performance",  label: "GPU Performance", icon: <Zap size={14} /> },
              { key: "ai_capabilities",  label: "AI Capabilities", icon: <Sparkles size={14} /> },
              { key: "efficiency",       label: "Power Efficiency", icon: <Zap size={14} /> },
              { key: "connectivity",     label: "Connectivity",    icon: <Cpu size={14} /> },
              { key: "gaming",           label: "Gaming",          icon: <Zap size={14} /> },
            ].filter(({ key }) => content[key]).map(({ key, label, icon }) => (
              <div key={key} className="card p-5">
                <div className="flex items-center gap-1.5 text-brand-400 text-xs font-semibold uppercase tracking-wider mb-2">
                  {icon} {label}
                </div>
                <p className="text-slate-300 text-sm leading-relaxed">{content[key]}</p>
              </div>
            ))}
          </div>

          {(content.pros || content.cons) && (
            <div className="grid sm:grid-cols-2 gap-4">
              {content.pros && (
                <div className="card p-5">
                  <h3 className="text-sm font-semibold text-green-400 mb-3">✅ Strengths</h3>
                  <ul className="space-y-1.5">
                    {(Array.isArray(content.pros) ? content.pros : [content.pros]).map((p: string, i: number) => (
                      <li key={i} className="text-sm text-slate-300 flex gap-2"><span className="text-green-500 shrink-0">•</span>{p}</li>
                    ))}
                  </ul>
                </div>
              )}
              {content.cons && (
                <div className="card p-5">
                  <h3 className="text-sm font-semibold text-red-400 mb-3">⚠️ Weaknesses</h3>
                  <ul className="space-y-1.5">
                    {(Array.isArray(content.cons) ? content.cons : [content.cons]).map((c: string, i: number) => (
                      <li key={i} className="text-sm text-slate-300 flex gap-2"><span className="text-red-500 shrink-0">•</span>{c}</li>
                    ))}
                  </ul>
                </div>
              )}
            </div>
          )}

          {content.verdict && (
            <div className="card p-5">
              <h3 className="text-sm font-semibold text-brand-400 mb-2">Verdict</h3>
              <p className="text-slate-200">{content.verdict}</p>
            </div>
          )}
        </div>
      ) : (
        <div className="card p-8 text-center">
          <Cpu size={36} className="text-slate-700 mx-auto mb-4" />
          <p className="text-slate-400 mb-2">AI insight for <span className="text-white font-semibold">{chipsetName}</span> hasn't been generated yet.</p>
          <p className="text-slate-600 text-sm">Head to the Admin → AI Insights panel to generate it.</p>
        </div>
      )}

      {/* Devices with chipset */}
      {devices && devices.length > 0 && (
        <div className="mt-10">
          <h2 className="text-lg font-bold text-white mb-4">Phones powered by {chipsetName}</h2>
          <div className="grid grid-cols-3 sm:grid-cols-4 md:grid-cols-6 gap-3">
            {devices.map((device: any) => (
              <Link key={device.id} href={`/devices/${device.slug}`} className="card p-2 hover:border-brand-500/50 transition-all group">
                <div className="aspect-square relative bg-[#0f172a] rounded-lg overflow-hidden mb-2">
                  {device.image_url ? (
                    <Image src={device.image_url} alt={device.name} fill className="object-contain p-1 group-hover:scale-105 transition-transform" sizes="96px" />
                  ) : <div className="w-full h-full flex items-center justify-center text-xl">📱</div>}
                </div>
                <p className="text-xs text-center text-slate-400 truncate">{device.name}</p>
              </Link>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}
