// @ts-nocheck
import type { Metadata } from "next";
import Link from "next/link";
import Image from "next/image";
import { Sparkles, Cpu, ChevronRight } from "lucide-react";
import { getAiInsight } from "@/lib/queries";
import { createClient } from "@/lib/supabase/server";

interface Props {
  params: Promise<{ slug: string }>;
}

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { slug } = await params;
  const name = slug.replace(/-/g, " ").replace(/\b\w/g, (c) => c.toUpperCase());
  return { title: `${name} — OS Insight`, description: `AI-powered deep dive into ${name} — features, history, performance, and more.` };
}

export default async function OsInsightPage({ params }: Props) {
  const { slug } = await params;
  const osName = slug.replace(/-/g, " ").replace(/\b\w/g, (c) => c.toUpperCase());
  const insight = await getAiInsight("os", slug);

  // Devices running this OS
  const supabase = await createClient();
  const { data: specRows } = await supabase
    .from("specifications")
    .select("device_id")
    .eq("spec_name", "OS")
    .ilike("spec_value", `%${osName.split(" ")[0]}%`)
    .limit(50);

  const deviceIds = [...new Set(specRows?.map((s) => s.device_id).filter(Boolean) ?? [])].slice(0, 12);

  const { data: devices } = deviceIds.length
    ? await supabase.from("devices").select("id,name,slug,image_url,company:companies(name,slug)").in("id", deviceIds)
    : { data: [] };

  const content = insight?.content as Record<string, any> | null;

  return (
    <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-10">
      <nav className="flex items-center gap-1.5 text-sm text-slate-500 mb-6">
        <Link href="/" className="hover:text-slate-300">Home</Link>
        <ChevronRight size={14} />
        <span className="text-slate-300">OS Insight: {osName}</span>
      </nav>

      {/* Header */}
      <div className="ai-glow rounded-2xl p-8 mb-8">
        <div className="flex items-center gap-2 text-brand-400 font-semibold mb-3">
          <Sparkles size={20} /> AI OS Insight
        </div>
        <h1 className="text-4xl font-bold text-white mb-3">{osName}</h1>
        {content?.tagline && <p className="text-slate-300 text-lg">{content.tagline}</p>}
        {insight && <p className="text-xs text-slate-600 mt-3">Generated by {insight.model_used} · {new Date(insight.generated_at).toLocaleDateString()}</p>}
      </div>

      {content ? (
        <div className="space-y-6">
          {/* Overview */}
          {content.overview && (
            <div className="card p-6">
              <h2 className="text-lg font-bold text-white mb-3">Overview</h2>
              <p className="text-slate-300 leading-relaxed">{content.overview}</p>
            </div>
          )}

          {/* Key sections grid */}
          <div className="grid sm:grid-cols-2 gap-4">
            {[
              { key: "history",     label: "History" },
              { key: "features",    label: "Key Features" },
              { key: "performance", label: "Performance" },
              { key: "ecosystem",   label: "Ecosystem" },
              { key: "security",    label: "Security" },
              { key: "updates",     label: "Update Policy" },
            ].filter(({ key }) => content[key]).map(({ key, label }) => (
              <div key={key} className="card p-5">
                <h3 className="text-sm font-semibold text-brand-400 uppercase tracking-wider mb-2">{label}</h3>
                <p className="text-slate-300 text-sm leading-relaxed">{content[key]}</p>
              </div>
            ))}
          </div>

          {/* Pros & Cons */}
          {(content.pros || content.cons) && (
            <div className="grid sm:grid-cols-2 gap-4">
              {content.pros && (
                <div className="card p-5">
                  <h3 className="text-sm font-semibold text-green-400 mb-3">✅ Strengths</h3>
                  <ul className="space-y-1.5">
                    {(Array.isArray(content.pros) ? content.pros : [content.pros]).map((p: string, i: number) => (
                      <li key={i} className="text-sm text-slate-300 flex gap-2"><span className="text-green-500 shrink-0">•</span>{p}</li>
                    ))}
                  </ul>
                </div>
              )}
              {content.cons && (
                <div className="card p-5">
                  <h3 className="text-sm font-semibold text-red-400 mb-3">⚠️ Weaknesses</h3>
                  <ul className="space-y-1.5">
                    {(Array.isArray(content.cons) ? content.cons : [content.cons]).map((c: string, i: number) => (
                      <li key={i} className="text-sm text-slate-300 flex gap-2"><span className="text-red-500 shrink-0">•</span>{c}</li>
                    ))}
                  </ul>
                </div>
              )}
            </div>
          )}

          {content.verdict && (
            <div className="card p-5 border-brand-500/30">
              <h3 className="text-sm font-semibold text-brand-400 mb-2">Verdict</h3>
              <p className="text-slate-200">{content.verdict}</p>
            </div>
          )}
        </div>
      ) : (
        <div className="card p-8 text-center">
          <Sparkles size={36} className="text-slate-700 mx-auto mb-4" />
          <p className="text-slate-400 mb-2">AI insight for <span className="text-white font-semibold">{osName}</span> hasn't been generated yet.</p>
          <p className="text-slate-600 text-sm">Head to the Admin → AI Insights panel to generate it.</p>
        </div>
      )}

      {/* Devices with this OS */}
      {devices && devices.length > 0 && (
        <div className="mt-10">
          <h2 className="text-lg font-bold text-white mb-4">Phones running {osName}</h2>
          <div className="grid grid-cols-3 sm:grid-cols-4 md:grid-cols-6 gap-3">
            {devices.map((device: any) => (
              <Link key={device.id} href={`/devices/${device.slug}`} className="card p-2 hover:border-brand-500/50 transition-all group">
                <div className="aspect-square relative bg-[#0f172a] rounded-lg overflow-hidden mb-2">
                  {device.image_url ? (
                    <Image src={device.image_url} alt={device.name} fill className="object-contain p-1 group-hover:scale-105 transition-transform" sizes="96px" />
                  ) : <div className="w-full h-full flex items-center justify-center text-xl">📱</div>}
                </div>
                <p className="text-xs text-center text-slate-400 truncate">{device.name}</p>
              </Link>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}
